<?xml version="1.0"?>
<!-- +X/L is forward, +Y/W is left, +Z/H is up -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Hunker">
	
	<xacro:property name="pitch" value="0.06"/>
	<xacro:property name="heightoffset" value="-2.5"/>
	<xacro:property name="effortlimit" value="1024"/>
	<xacro:property name="velocitylimit" value="0.5"/>

	<xacro:macro name="white">
		<material name="white"><color rgba="0.875 0.875 0.875 1.0"/></material>
	</xacro:macro>
	<xacro:macro name="black">
		<material name="black"><color rgba="0.125 0.125 0.125 1.0"/></material>
	</xacro:macro>
	<xacro:macro name="blue">
		<material name="blue"><color rgba="0.125 0.125 1.0 1.0"/></material>
	</xacro:macro>
	<xacro:macro name="mud">
		<material name="mud"><color rgba="0.5 0.5 0.0 1.0"/></material>
	</xacro:macro>
	<xacro:macro name="translucent">
		<material name="translucent"><color rgba="0.5 0.5 0.5 1.0"/></material>
	</xacro:macro>

	<xacro:macro name="plate" params="l w h x y z *material">
		<visual>
			<geometry>
				<box size="${l*pitch} ${w*pitch} ${h*pitch}"/>
			</geometry>
			<origin xyz="${x*pitch} ${y*pitch} ${z*pitch}"/>
			<xacro:insert_block name="material"/>
		</visual>
	</xacro:macro>
	<xacro:macro name="wheelX" params="x y z *material">
		<visual>
			<geometry>
				<cylinder length="${0.5*pitch}" radius="${1.5*pitch}"/>
			</geometry>
			<origin  xyz="${x*pitch} ${y*pitch} ${z*pitch}" rpy="0 ${pi/2} 0"/>
			<xacro:insert_block name="material"/>
		</visual>
	</xacro:macro>
	<xacro:macro name="wheelY" params="x y z *material">
		<visual>
			<geometry>
				<cylinder length="${0.5*pitch}" radius="${1.5*pitch}"/>
			</geometry>
			<origin  xyz="${x*pitch} ${y*pitch} ${z*pitch}" rpy="${pi/2} 0 0"/>
			<xacro:insert_block name="material"/>
		</visual>
	</xacro:macro>
	<xacro:macro name="wheelZ" params="x y z *material">
		<visual>
			<geometry>
				<cylinder length="${0.5*pitch}" radius="${1.5*pitch}"/>
			</geometry>
			<origin  xyz="${x*pitch} ${y*pitch} ${z*pitch}"/>
			<xacro:insert_block name="material"/>
		</visual>
	</xacro:macro>



	<link name="base_link">
		<xacro:plate l="5" w="5" h="0.5" x="0" y="0" z="${-2.25 - heightoffset}"><xacro:blue/></xacro:plate>
		<xacro:plate l="5" w="5" h="0.5" x="0" y="0" z="${2.25 - heightoffset}"><xacro:blue/></xacro:plate>

		<xacro:plate l="6" w="4" h="4" x="-4.5" y="0" z="${0 - heightoffset}"><xacro:translucent/></xacro:plate>
		<xacro:plate l="4" w="6" h="4" x="0" y="4.5" z="${0 - heightoffset}"><xacro:translucent/></xacro:plate>
		<xacro:plate l="4" w="6" h="4" x="0" y="-4.5" z="${0 - heightoffset}"><xacro:translucent/></xacro:plate>
		<xacro:plate l="6" w="4" h="4" x="4.5" y="0" z="${0 - heightoffset}"><xacro:translucent/></xacro:plate>
	</link>

	<xacro:macro name="leg" params="name x y z rpy reflect:=1">
		<link name="${name}Hip">
			<xacro:wheelZ x="0" y="0" z="0.25"><xacro:black/></xacro:wheelZ>

			<xacro:plate l="7" w="3" h="0.5" x="-3" y="0" z="0.75"><xacro:mud/></xacro:plate>
			<xacro:plate l="5" w="3" h="0.5" x="-4" y="0" z="0.25"><xacro:mud/></xacro:plate>
			<xacro:plate l="7" w="1" h="0.5" x="-3" y="0" z="-4.25"><xacro:mud/></xacro:plate>

			<xacro:plate l="6" w="4" h="4" x="-4.5" y="0" z="-2"><xacro:translucent/></xacro:plate>
		</link>
		<joint name="${name}AimingHip" type="revolute">
			<parent link="base_link"/>
			<child link="${name}Hip"/>
			<axis xyz="0 0 1"/>
			<limit effort="${effortlimit}" lower="${-78*pi/180}" upper="${78*pi/180}" velocity="${velocitylimit}"/>
			<origin xyz="${x*pitch} ${y*pitch} ${z*pitch}" rpy="${rpy}"/>
		</joint>
		<link name="${name}Thigh">
			<xacro:wheelY x="0" y="${0.25*reflect}" z="0"><xacro:black/></xacro:wheelY>

			<xacro:plate l="7" w="0.5" h="3" x="-3" y="${0.75*reflect}" z="0"><xacro:mud/></xacro:plate>
			<xacro:plate l="7" w="0.5" h="2" x="-3" y="${-4.25*reflect}" z="-0.5"><xacro:mud/></xacro:plate>

			<xacro:wheelY x="-6" y="${0.25*reflect}" z="0"><xacro:black/></xacro:wheelY>
		</link>
		<joint name="${name}LiftingHip" type="revolute">
			<parent link="${name}Hip"/>
			<child link="${name}Thigh"/>
			<axis xyz="0 ${1 * reflect} 0"/>
			<limit effort="${effortlimit}" lower="${-125*pi/180}" upper="${125*pi/180}" velocity="${velocitylimit}"/>
			<origin xyz="${-6*pitch} ${2*reflect*pitch} ${-2*pitch}"/>
		</joint>
		<link name="${name}Calf">
			<xacro:plate l="6" w="4" h="4" x="-1.5" y="${-2*reflect}" z="0"><xacro:translucent/></xacro:plate>
		</link>
		<joint name="${name}Knee" type="revolute">
			<parent link="${name}Thigh"/>
			<child link="${name}Calf"/>
			<axis xyz="0 ${-1 * reflect} 0"/>
			<limit effort="${effortlimit}" lower="${-130*pi/180}" upper="${130*pi/180}" velocity="${velocitylimit}"/>
			<origin xyz="${-6*pitch} 0 0"/>
		</joint>
		<link name="${name}Foot">
			<xacro:wheelY x="1.5" y="2.25" z="0"><xacro:mud/></xacro:wheelY>
			<xacro:wheelY x="1.5" y="-2.25" z="0"><xacro:mud/></xacro:wheelY>
		</link>
		<joint name="${name}Ankle" type="fixed">
			<parent link="${name}Calf"/>
			<child link="${name}Foot"/>
			<origin xyz="${-5.5 * pitch} ${-2 * reflect * pitch} 0"/>
		</joint>
	</xacro:macro>

	<xacro:leg name="backRight" x="-6" y="0" z="${2 - heightoffset}" rpy="0 0 0"/>
	<xacro:leg name="backLeft" x="0" y="6" z="${2 - heightoffset}" rpy="0 0 ${-pi/2}" reflect="-1"/>
	<xacro:leg name="frontRight" x="0" y="-6" z="${2 - heightoffset}" rpy="0 0 ${pi/2}"/>
	<xacro:leg name="frontLeft" x="6" y="0" z="${2 - heightoffset}" rpy="0 0 ${pi}" reflect="-1"/>
</robot>
