BOARD = opencm904
BOOTLOADER = robotis

SRC_FILES = main.cpp
USER_MODULES = $(CURDIR)/../../Libraries/ToyWalker
USER_INCLUDES = $(CURDIR)/../../Libraries/Eigen31

include ../common.mk

include $(RHOBANMAPLE_DIR)/skeleton/Makefile
