BOARD = opencm904
BOOTLOADER = robotis

SRC_FILES = main.cpp
USER_MODULES = ../../Libraries/ToyWalker
USER_INCLUDES = ../../Libraries/Eigen31

include ../common.mk

include $(RHOBANMAPLE_DIR)/skeleton/Makefile
